# A function to make ggplots the proper way
require(ggplot2)
makeGGplotGraph = function(dataFrameOfResult, xAxis, yAxis, main) {
  # Take a dataframe of the data to be graphed, Column number of threshold element 1, threshold element 2
  # Third argument is the title
  
  # Generate a vector to define which elements will be coloured differently as a threshold.
  # Change the thresholds here within the function
  dataFrameOfResult$threshold = as.factor(abs(dataFrameOfResult$yAxis > 2 & dataFrameOfResult$yAxis < 0.05))
  
  # Make the plot object
  g = ggplot(data=dataFrameOfResult, aes(x=xAxis, y=-log10(yAxis), colour=threshold)) +
    geom_point(alpha=0.80, size=2) +
    opts(legend.position = "none", title=(main)
    ) +
    #Add some custome limits to the axes here
    #xlim(c(-5, 5)) + ylim(c(0, 50)) +
    xlab(as.character(xAxis)) + ylab(as.character(yAxis))
  return (g)
}

addTexttoGGplot = function(ggplotObject, dataFrameOfResult, xAxis, yAxis, name) {
  # Take the ggplot object generated by the makeGGplotGraph function and add text to it
  # Last argument is the name of the column containing names
  
  # The subset of genes which will be labelled on the graph itself. Again change these parameters
  dd_text = dataFrameOfResult[(abs(dataFrameOfResult$xAxis) > 5) & (dataFrameOfResult$yAxis < 0.001),]
  # Draw text
  ggplotObject + geom_text(data = dd_text, aes(x=xAxis, y=-log10(yAxis),
                                    label=name, size=0.2), colour="black")
  return (ggplotObject)
}

# Write this code in your main script
#g = makeGGplotGraph(Function arguments)
#g
#addTexttoGGplot()