library(biomaRt)

mart<- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))

annotateIds = function(geneList)  { 
  # Given a gene list return the ENSEMBL information and ID mappings
  ensembl_genes = row.names(geneList)
  list=getBM(
    filters="ensembl_gene_id", 
    attributes=c("ensembl_gene_id", "external_gene_id", "description"),
    values= ensembl_genes,
    mart= mart)
  return (list)
}

# A function to run the mappings
ensembl_2_geneName <- function(topTable) {
  # Given a dataframe generated by topTale, return a list of differentially expressed genes return the geneID
  annResult = annotateIds(topTable)
  topTable$ensembl_id = row.names(topTable)
  result = merge.data.frame(annResult, topTable, by.x='ensembl_gene_id', by.y='ensembl_id')
  return (result)
}