### Script to make logR heatmaps CNV pipeline Parveen
#########################################################
### A) Installing and loading required packages
#########################################################

if (!require("gplots")) {
    install.packages("gplots", dependencies = TRUE, repos='http://cran.us.r-project.org')
    library(gplots)
}
if (!require("RColorBrewer")) {
    install.packages("RColorBrewer", dependencies = TRUE, repos='http://cran.us.r-project.org')
    library(RColorBrewer)
}
if (!require("randomcoloR")) {
    install.packages("randomcoloR", dependencies = TRUE, repos='http://cran.us.r-project.org')
    library(randomcoloR)
}
#########################################################
### B) Combine multiple text files 
#########################################################

### Adjust path to folder containng the logR text files generated by parveens pipeline
basedir <- "/Users/u0107775/Data/GandT_Seq/170925_MEL06_GandT/171107_MEL06_DNA/Results/results_ploidy2_ref3/bins/unsure/"
setwd(basedir)
pat <- ".segments.copynumber.txt"
tophat.all <- list.files(path = basedir,
                         pattern = pat,
                         all.files = TRUE,
                         recursive = FALSE,
                         ignore.case = FALSE,
                         include.dirs = FALSE)

# we choose the 'all' series
myfiles = tophat.all
DT <- list()

# read each file as array element of DT and rename the last 2 cols
# we created a list of single sample tables
for (i in 1:length(myfiles) ) {
    test=read.table(myfiles[i], header = T, stringsAsFactors = FALSE, sep="\t")
    test$id=paste(test$chr,test$end, sep = "_", collapse = NULL)
    DT[[myfiles[i]]] <- test[,c(8,4)]
    cnts <- as.character(substr(myfiles[i],1,32))
    colnames(DT[[myfiles[i]]]) <- c("ID", cnts)
}

###display number of bins per chr => determine number of bins you need to take together to get a 
# intepretable heatmap (preferable 25 bins for chr 1)
bins=test[,"chr"]
tb_bin=table(bins)
tb_bin[1]
x_bin=round(tb_bin[1]/25)

# merge all elements based on first ID columns
data <- DT[[myfiles[1]]]

# inspect
head(data)

# we now add each other table with the ID column as key
for (i in 2:length(myfiles)) {
    y <- DT[[myfiles[i]]]
    z <- merge(data, y, by = c("ID"))
    data <- z
}

# ID column becomes rownames
rownames(data) <- data$ID
data <- data[,-1]

rn <- rownames(data)
m1 <- do.call(rbind, strsplit(rn, '_'))
data$chr <- m1[,1]
data$position <- m1[,2]
data$chr <- as.numeric(data$chr)
data$position <- as.numeric(data$position)
data1=data[ order(data$chr, data$position), ]
data1$chr[is.na(data1$chr)] <- "X"

### downsampling bins => nrow determines the number of bins taken together for the heatmap
chr1=(data1[data1$chr==1,])
chr1$chr <- NULL
Down_chr1=as.data.frame(sapply(chr1, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr1)=paste("chr1",Down_chr1$position, sep = "_", collapse = NULL)
chr1$position <- NULL


chr2=(data1[data1$chr==2,])
chr2$chr <- NULL
Down_chr2=as.data.frame(sapply(chr2, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr2)=paste("chr2",Down_chr2$position, sep = "_", collapse = NULL)
chr2$position <- NULL

chr3=(data1[data1$chr==3,])
chr3$chr <- NULL
Down_chr3=as.data.frame(sapply(chr3, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr3)=paste("chr3",Down_chr3$position, sep = "_", collapse = NULL)
chr3$position <- NULL

chr4=(data1[data1$chr==4,])
chr4$chr <- NULL
Down_chr4=as.data.frame(sapply(chr4, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr4)=paste("chr4",Down_chr4$position, sep = "_", collapse = NULL)
chr4$position <- NULL


chr5=(data1[data1$chr==5,])
chr5$chr <- NULL
Down_chr5=as.data.frame(sapply(chr5, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr5)=paste("chr5",Down_chr5$position, sep = "_", collapse = NULL)
chr5$position <- NULL

chr6=(data1[data1$chr==6,])
chr6$chr <- NULL
Down_chr6=as.data.frame(sapply(chr6, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr6)=paste("chr6",Down_chr6$position, sep = "_", collapse = NULL)
chr6$position <- NULL


chr7=(data1[data1$chr==7,])
chr7$chr <- NULL
Down_chr7=as.data.frame(sapply(chr7, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr7)=paste("chr7",Down_chr7$position, sep = "_", collapse = NULL)
chr7$position <- NULL


chr8=(data1[data1$chr==8,])
chr8$chr <- NULL
Down_chr8=as.data.frame(sapply(chr8, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr8)=paste("chr8",Down_chr8$position, sep = "_", collapse = NULL)
chr8$position <- NULL

chr9=(data1[data1$chr==9,])
chr9$chr <- NULL
Down_chr9=as.data.frame(sapply(chr9, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr9)=paste("chr9",Down_chr9$position, sep = "_", collapse = NULL)
chr9$position <- NULL

chr10=(data1[data1$chr==10,])
chr10$chr <- NULL
Down_chr10=as.data.frame(sapply(chr10, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr10)=paste("chr10",Down_chr10$position, sep = "_", collapse = NULL)
chr10$position <- NULL

chr11=(data1[data1$chr==11,])
chr11$chr <- NULL
Down_chr11=as.data.frame(sapply(chr11, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr11)=paste("chr11",Down_chr11$position, sep = "_", collapse = NULL)
chr11$position <- NULL


chr12=(data1[data1$chr==12,])
chr12$chr <- NULL
Down_chr12=as.data.frame(sapply(chr12, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr12)=paste("chr12",Down_chr12$position, sep = "_", collapse = NULL)
chr12$position <- NULL


chr13=(data1[data1$chr==13,])
chr13$chr <- NULL
Down_chr13=as.data.frame(sapply(chr13, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr13)=paste("chr13",Down_chr13$position, sep = "_", collapse = NULL)
chr13$position <- NULL


chr14=(data1[data1$chr==14,])
chr14$chr <- NULL
Down_chr14=as.data.frame(sapply(chr14, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr14)=paste("chr14",Down_chr14$position, sep = "_", collapse = NULL)
chr14$position <- NULL


chr15=(data1[data1$chr==15,])
chr15$chr <- NULL
Down_chr15=as.data.frame(sapply(chr15, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr15)=paste("chr15",Down_chr15$position, sep = "_", collapse = NULL)
chr15$position <- NULL

chr16=(data1[data1$chr==16,])
chr16$chr <- NULL
Down_chr16=as.data.frame(sapply(chr16, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr16)=paste("chr16",Down_chr16$position, sep = "_", collapse = NULL)
chr16$position <- NULL

chr17=(data1[data1$chr==17,])
chr17$chr <- NULL
Down_chr17=as.data.frame(sapply(chr17, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr17)=paste("chr17",Down_chr17$position, sep = "_", collapse = NULL)
chr17$position <- NULL

chr18=(data1[data1$chr==18,])
chr18$chr <- NULL
Down_chr18=as.data.frame(sapply(chr18, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr18)=paste("chr18",Down_chr18$position, sep = "_", collapse = NULL)
chr18$position <- NULL

chr19=(data1[data1$chr==19,])
chr19$chr <- NULL
Down_chr19=as.data.frame(sapply(chr19, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr19)=paste("chr19",Down_chr19$position, sep = "_", collapse = NULL)
chr19$position <- NULL

chr20=(data1[data1$chr==20,])
chr20$chr <- NULL
Down_chr20=as.data.frame(sapply(chr20, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr20)=paste("chr20",Down_chr20$position, sep = "_", collapse = NULL)
chr20$position <- NULL


chr21=(data1[data1$chr==21,])
chr21$chr <- NULL
Down_chr21=as.data.frame(sapply(chr21, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr21)=paste("chr21",Down_chr21$position, sep = "_", collapse = NULL)
chr21$position <- NULL

chr22=(data1[data1$chr==22,])
chr22$chr <- NULL
Down_chr22=as.data.frame(sapply(chr22, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chr22)=paste("chr22",Down_chr22$position, sep = "_", collapse = NULL)
chr22$position <- NULL

chrX=(data1[data1$chr=="X",])
chrX$chr <- NULL
Down_chrX=as.data.frame(sapply(chrX, function(x) colMeans(matrix(x, nrow=x_bin))))
row.names(Down_chrX)=paste("chrX",Down_chrX$position, sep = "_", collapse = NULL)
chrX$position <- NULL

Data2=rbind(Down_chr1,Down_chr2,Down_chr3,Down_chr4,Down_chr5,Down_chr6,Down_chr7,Down_chr8,Down_chr9,Down_chr10,Down_chr11,Down_chr12,Down_chr13,Down_chr14,Down_chr15,Down_chr16,Down_chr17,Down_chr18,Down_chr19,Down_chr20,Down_chr21,Down_chr22,Down_chrX)

data1$chr <- NULL
data1$position <- NULL
Data2$position <- NULL

xx <- gsub("*_.*", "\\1", colnames(Data2))
n <- 4
palette <- distinctColorPalette(n)
l2cols <- palette[as.integer(factor(xx, levels = c("BL1sc", "BL1sn", "HCC38sc", "HCC38sn")))]
yy <- gsub("*_.*", "\\1", rownames(Data2))
n <- 23
zz <- gsub("*_*_.*_", '', colnames(Data2))
z = gsub("T[0-9]P[0-9]", '', zz)
nameLabels=gsub("50", '', z)
palette <- distinctColorPalette(n)
l2rows <- palette[as.integer(factor(yy, levels = c("chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", "chr22", "chrX")))]
labrows=c("chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", "chr22", "chrX")
#########################################################
### C) Customizing and plotting the heat map
#########################################################

# creates a own color palette from red to green
my_palette <- colorRampPalette(c("blue", "white", "red"))(n = 299) ##adjust for other color key

# (optional) defines the color breaks manually for a "skewed" color transition
col_breaks = c(seq(0,1.19,length=100),  # for red
               seq(1.2,2.8,length=100),           # for yellow
               seq(2.81,8,length=100))             # for green

# creates a 5 x 5 inch image
png("./plot2.png",    # create PNG for the heat map        
    width = 5*300,        # 5 x 300 pixels
    height = 5*300,
    res = 300,            # 300 pixels per inch
    pointsize = 6)        # smaller font size

test=(data.matrix(Data2, rownames.force = NA))
heatmap.2(test,
          main = "CNV heatmap: single-cell vs single-nuclei", # heat map title
          #density.info="none",  # turns off density plot inside color legend
          trace="none",         # turns off trace lines inside the heat map
          margins =c(10,12),     # widens margins around plot
          col=my_palette,       # use on color palette defined earlier
          breaks=col_breaks,    # enable color transition at specified limits
          dendrogram="col",
          Rowv=FALSE,
          ColSideColors=l2cols,
          labCol = F,
          RowSideColors = l2rows,
          labRow = FALSE)

legend("left",      
       legend = unique(xx),
       col = unique(l2cols), 
       lty= 1,             
       lwd = 5,           
       cex=.7
)

dev.off()               # close the PNG device