---
title: "Feature Selection"
description: |
  Choose the genes that are interesting for analysis
author: "Daniel Brown"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      smooth_scroll: true
    theme: readable
    highlight: tango 
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.asp=0.618, 
                      fig.path='/Figures/NNxx/FeatureSelection/',
                      warning=FALSE, message=FALSE)
```

```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(scater)
library(scran)
library(DT)
```

# Read single-cell experiment object

```{r}
sce <- readRDS(here(
  "Path to sce"
))
```

# Normalization by deconvolution
* Pre-clustering further improves size factors estimates by normalizing 'similar' cells together
* quickCluster() performs simulations, so need to 'set the seed' to obtain reproducible results

```{r}
set.seed(666)
clust <- quickCluster(sce) 

# Compute deconvolution size factors
deconv.sf <- calculateSumFactors(sce, 
  cluster=clust, min.mean=0.1)
deconv.sf.zeisel <- calculateSumFactors(sce.zeisel, cluster=clust.zeisel)
```

# Examine distribution of size factors
```{r deconv}
summary(deconv.sf)
hist(log10(deconv.sf),
  xlab="Log10[Size factor]", 
  col="grey80")
```

# Scaling and log-transforming
```{r}
# Using the convolution size factors we computed earlier
sce <- computeSumFactors(sce, cluster=clust, min.mean=0.1)
sce <- logNormCounts(sce)
assayNames(sce.zeisel)
```


# Cleanup
```{r}
saveRDS(sce,
        here(
          "path_to_file"
        ))
sessionInfo()
```